+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Sun Dec  4 00:03:14 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL openvswitch-ovn-vtep
+ pkgs=openvswitch-ovn-vtep
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs openvswitch-ovn-vtep --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp6uwsctyu
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp6uwsctyu
+ service=ovn-controller-vtep.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-04 00:04:05'
+ flag=false
++ getenforce
++ grep Enforcing
+ '[' ']'
+ userdel -rf openvswitch_ovn
userdel: user 'openvswitch_ovn' does not exist
+ useradd openvswitch_ovn
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Sun Dec  4 00:04:07 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Sun Dec  4 00:04:08 2022 - INFO  - Start testing...
+ su - openvswitch_ovn
spawn service ovn-controller-vtep.service restart
Redirecting to /bin/systemctl restart ovn-controller-vtep.service
Failed to connect to bus: No such file or directory
send: spawn id exp4 not open
    while executing
"send "anolisos\n""
+ grep -iE 'fail|error' /tmp/testlog1
Failed to connect to bus: No such file or directory
+ CHECK_RESULT 0 1 0 'ovn-controller-vtep.service restart failed'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='ovn-controller-vtep.service restart failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'ovn-controller-vtep.service restart failed'
+ LOG_ERROR 'ovn-controller-vtep.service restart failed'
+ message='ovn-controller-vtep.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ovn-controller-vtep.service restart failed'
Sun Dec  4 00:04:12 2022 - ERROR - ovn-controller-vtep.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovn-controller-vtep.sh line 49'
+ message='oe_test_service_ovn-controller-vtep.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovn-controller-vtep.sh line 49'
Sun Dec  4 00:04:13 2022 - ERROR - oe_test_service_ovn-controller-vtep.sh line 49
+ return 0
+ su - openvswitch_ovn
spawn service ovn-controller-vtep.service stop
Redirecting to /bin/systemctl stop ovn-controller-vtep.service
Failed to connect to bus: No such file or directory
send: spawn id exp4 not open
    while executing
"send "anolisos\n""
+ grep -iE 'fail|error' /tmp/testlog2
Failed to connect to bus: No such file or directory
+ CHECK_RESULT 0 1 0 'ovn-controller-vtep.service stop failed'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='ovn-controller-vtep.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'ovn-controller-vtep.service stop failed'
+ LOG_ERROR 'ovn-controller-vtep.service stop failed'
+ message='ovn-controller-vtep.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ovn-controller-vtep.service stop failed'
Sun Dec  4 00:04:16 2022 - ERROR - ovn-controller-vtep.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovn-controller-vtep.sh line 61'
+ message='oe_test_service_ovn-controller-vtep.sh line 61'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovn-controller-vtep.sh line 61'
Sun Dec  4 00:04:17 2022 - ERROR - oe_test_service_ovn-controller-vtep.sh line 61
+ return 0
+ SLEEP_WAIT 10
+ wait_time=10
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 10 --cmd '' --mode 1
+ su - openvswitch_ovn
spawn service ovn-controller-vtep.service start
Redirecting to /bin/systemctl start ovn-controller-vtep.service
Failed to connect to bus: No such file or directory
send: spawn id exp4 not open
    while executing
"send "anolisos\n""
+ grep -iE 'fail|error' /tmp/testlog3
Failed to connect to bus: No such file or directory
+ CHECK_RESULT 0 1 0 'ovn-controller-vtep.service start failed'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='ovn-controller-vtep.service start failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'ovn-controller-vtep.service start failed'
+ LOG_ERROR 'ovn-controller-vtep.service start failed'
+ message='ovn-controller-vtep.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ovn-controller-vtep.service start failed'
Sun Dec  4 00:04:30 2022 - ERROR - ovn-controller-vtep.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovn-controller-vtep.sh line 74'
+ message='oe_test_service_ovn-controller-vtep.sh line 74'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovn-controller-vtep.sh line 74'
Sun Dec  4 00:04:31 2022 - ERROR - oe_test_service_ovn-controller-vtep.sh line 74
+ return 0
+ su - openvswitch_ovn -c 'service ovn-controller-vtep.service status'
+ grep 'Active: active (running)'
Redirecting to /bin/systemctl status ovn-controller-vtep.service
Failed to connect to bus: No such file or directory
+ CHECK_RESULT 1 0 0 'ovn-controller-vtep.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ovn-controller-vtep.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ovn-controller-vtep.service start failed'
+ LOG_ERROR 'ovn-controller-vtep.service start failed'
+ message='ovn-controller-vtep.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ovn-controller-vtep.service start failed'
Sun Dec  4 00:04:33 2022 - ERROR - ovn-controller-vtep.service start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovn-controller-vtep.sh line 76'
+ message='oe_test_service_ovn-controller-vtep.sh line 76'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovn-controller-vtep.sh line 76'
Sun Dec  4 00:04:34 2022 - ERROR - oe_test_service_ovn-controller-vtep.sh line 76
+ return 0
+ journalctl --since '2022-12-04 00:04:05' -u ovn-controller-vtep.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ grep -v -i '[FAILED]'
+ CHECK_RESULT 1 1 0 'There is an error message for the log of ovn-controller-vtep.service'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='There is an error message for the log of ovn-controller-vtep.service'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ su - openvswitch_ovn
spawn service ovn-controller-vtep.service reload
Redirecting to /bin/systemctl reload ovn-controller-vtep.service
Failed to connect to bus: No such file or directory
send: spawn id exp4 not open
    while executing
"send "anolisos\n""
+ grep 'Job type reload is not applicable for unit ovn-controller-vtep.service' /tmp/testlog4
+ CHECK_RESULT 1 0 0 'ovn-controller-vtep.service reload failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ovn-controller-vtep.service reload failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ovn-controller-vtep.service reload failed'
+ LOG_ERROR 'ovn-controller-vtep.service reload failed'
+ message='ovn-controller-vtep.service reload failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ovn-controller-vtep.service reload failed'
Sun Dec  4 00:04:37 2022 - ERROR - ovn-controller-vtep.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ovn-controller-vtep.sh line 90'
+ message='oe_test_service_ovn-controller-vtep.sh line 90'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ovn-controller-vtep.sh line 90'
Sun Dec  4 00:04:38 2022 - ERROR - oe_test_service_ovn-controller-vtep.sh line 90
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Sun Dec  4 00:04:39 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sun Dec  4 00:04:40 2022 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Sun Dec  4 00:04:40 2022 - INFO  - start environment cleanup.
+ su - openvswitch_ovn
spawn systemctl stop ovn-controller-vtep.service
Failed to connect to bus: No such file or directory
send: spawn id exp3 not open
    while executing
"send "anolisos\n""
+ userdel -rf openvswitch_ovn
+ '[' false = true ']'
+ rm -rf /tmp/testlog1 /tmp/testlog2 /tmp/testlog3 /tmp/testlog4
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp6uwsctyu ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp6uwsctyu
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Sun Dec  4 00:04:59 2022 - INFO  - Finish environment cleanup!
