+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Jan  5 21:34:43 2023 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_monitor_dictionary_access.sh: line 25: service: command not found
+ auditctl -D
oe_test_audit_monitor_dictionary_access.sh: line 26: auditctl: command not found
+ CHECK_RESULT 127 0 0 'delete failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu Jan  5 21:34:44 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_dictionary_access.sh line 27'
+ message='oe_test_audit_monitor_dictionary_access.sh line 27'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_dictionary_access.sh line 27'
Thu Jan  5 21:34:45 2023 - ERROR - oe_test_audit_monitor_dictionary_access.sh line 27
+ return 0
+ auditctl -w /opt -p wa -k opt_changes
oe_test_audit_monitor_dictionary_access.sh: line 28: auditctl: command not found
+ CHECK_RESULT 127 0 0 'add failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='add failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'add failed'
+ LOG_ERROR 'add failed'
+ message='add failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'add failed'
Thu Jan  5 21:34:47 2023 - ERROR - add failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_dictionary_access.sh line 29'
+ message='oe_test_audit_monitor_dictionary_access.sh line 29'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_dictionary_access.sh line 29'
Thu Jan  5 21:34:48 2023 - ERROR - oe_test_audit_monitor_dictionary_access.sh line 29
+ return 0
+ auditctl -l
+ grep -e '-w /opt -p wa -k opt_changes'
oe_test_audit_monitor_dictionary_access.sh: line 30: auditctl: command not found
+ CHECK_RESULT 1 0 0 'change failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='change failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'change failed'
+ LOG_ERROR 'change failed'
+ message='change failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'change failed'
Thu Jan  5 21:34:49 2023 - ERROR - change failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_dictionary_access.sh line 31'
+ message='oe_test_audit_monitor_dictionary_access.sh line 31'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_dictionary_access.sh line 31'
Thu Jan  5 21:34:50 2023 - ERROR - oe_test_audit_monitor_dictionary_access.sh line 31
+ return 0
++ date +%T
+ starttime=21:34:50
+ mkdir -p /opt/test/
+ CHECK_RESULT 0 0 0 'create failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='create failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ date +%T
+ endtime=21:34:50
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ ausearch -ts 21:34:50 -te 21:34:50 -f /opt -k opt_changes
oe_test_audit_monitor_dictionary_access.sh: line 37: ausearch: command not found
+ CHECK_RESULT 127 0 0 'ausearch failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='ausearch failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'ausearch failed'
+ LOG_ERROR 'ausearch failed'
+ message='ausearch failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ausearch failed'
Thu Jan  5 21:34:54 2023 - ERROR - ausearch failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_dictionary_access.sh line 38'
+ message='oe_test_audit_monitor_dictionary_access.sh line 38'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_dictionary_access.sh line 38'
Thu Jan  5 21:34:55 2023 - ERROR - oe_test_audit_monitor_dictionary_access.sh line 38
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Jan  5 21:34:56 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Jan  5 21:34:57 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Jan  5 21:34:58 2023 - INFO  - Start to restore the test environment.
+ auditctl -D
oe_test_audit_monitor_dictionary_access.sh: line 44: auditctl: command not found
+ rm -rf /opt/test
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Jan  5 21:35:00 2023 - INFO  - End to restore the test environment.
