+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Jan  5 21:35:55 2023 - INFO  - Start to prepare the test environment.
+ useradd Jevons
++ id -u Jevons
+ uid=1001
+ LOG_INFO 'End to prepare the environment'
+ message='End to prepare the environment'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the environment'
Thu Jan  5 21:35:56 2023 - INFO  - End to prepare the environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Jan  5 21:35:58 2023 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_monitor_do_command.sh: line 31: service: command not found
+ auditctl -D
oe_test_audit_monitor_do_command.sh: line 32: auditctl: command not found
+ CHECK_RESULT 127 0 0 'clean failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='clean failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'clean failed'
+ LOG_ERROR 'clean failed'
+ message='clean failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'clean failed'
Thu Jan  5 21:35:59 2023 - ERROR - clean failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_do_command.sh line 33'
+ message='oe_test_audit_monitor_do_command.sh line 33'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_do_command.sh line 33'
Thu Jan  5 21:36:00 2023 - ERROR - oe_test_audit_monitor_do_command.sh line 33
+ return 0
+ auditctl -a always,exit -S execve -F uid=1001 -k command
oe_test_audit_monitor_do_command.sh: line 34: auditctl: command not found
+ CHECK_RESULT 127 0 0 'add rule failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='add rule failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'add rule failed'
+ LOG_ERROR 'add rule failed'
+ message='add rule failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'add rule failed'
Thu Jan  5 21:36:01 2023 - ERROR - add rule failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_do_command.sh line 35'
+ message='oe_test_audit_monitor_do_command.sh line 35'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_do_command.sh line 35'
Thu Jan  5 21:36:02 2023 - ERROR - oe_test_audit_monitor_do_command.sh line 35
+ return 0
+ auditctl -l
oe_test_audit_monitor_do_command.sh: line 36: auditctl: command not found
+ grep -e '-a always,exit -S execve -F uid=1001'
+ CHECK_RESULT 1 0 0 'grep failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep failed'
+ LOG_ERROR 'grep failed'
+ message='grep failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'grep failed'
Thu Jan  5 21:36:04 2023 - ERROR - grep failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_do_command.sh line 37'
+ message='oe_test_audit_monitor_do_command.sh line 37'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_do_command.sh line 37'
Thu Jan  5 21:36:05 2023 - ERROR - oe_test_audit_monitor_do_command.sh line 37
+ return 0
++ date +%T
+ starttime=21:36:05
+ su - Jevons -c pwd
/home/Jevons
+ CHECK_RESULT 0 0 0 'login failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='login failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ date +%T
+ endtime=21:36:09
+ ausearch -ts 21:36:05 -te 21:36:09 -k command
+ grep pwd
oe_test_audit_monitor_do_command.sh: line 42: ausearch: command not found
+ CHECK_RESULT 1 0 0 'ausearch failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ausearch failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ausearch failed'
+ LOG_ERROR 'ausearch failed'
+ message='ausearch failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ausearch failed'
Thu Jan  5 21:36:10 2023 - ERROR - ausearch failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_do_command.sh line 43'
+ message='oe_test_audit_monitor_do_command.sh line 43'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_do_command.sh line 43'
Thu Jan  5 21:36:12 2023 - ERROR - oe_test_audit_monitor_do_command.sh line 43
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Jan  5 21:36:13 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Jan  5 21:36:14 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ fOG_INFO 'Start to restore the test environment.'
oe_test_audit_monitor_do_command.sh: line 48: fOG_INFO: command not found
+ userdel -rf Jevons
+ auditctl -D
oe_test_audit_monitor_do_command.sh: line 50: auditctl: command not found
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Jan  5 21:36:15 2023 - INFO  - End to restore the test environment.
