+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Mon Dec  5 08:10:59 2022 - INFO  - Start environmental preparation.
++ hostname
+ host_name=anolis-riscv
+ hostname OE-TESTD
+ echo '127.0.0.1 TESTAD.LOCAL'
+ DNF_INSTALL 'samba-dc python3-samba-dc krb5-server'
+ pkgs='samba-dc python3-samba-dc krb5-server'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'samba-dc python3-samba-dc krb5-server' --node 1 --tempfile ''
Mon Dec  5 08:11:10 2022 - ERROR - pkgs:(samba-dc python3-samba-dc) not found
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ mv /etc/samba/smb.conf /etc/samba/smb.conf_bak
mv: cannot stat '/etc/samba/smb.conf': No such file or directory
+ expect
spawn samba-tool domain provision --use-rfc2307 --interactive --function-level=2008_R2
couldn't execute "samba-tool": no such file or directory
    while executing
"spawn samba-tool domain provision --use-rfc2307 --interactive --function-level=2008_R2"
+ mv /etc/krb5.conf /etc/krb5.bak
+ rm -rf /etc/krb5.conf
+ cp -raf /var/lib/samba/private/krb5.conf /etc/
cp: cannot stat '/var/lib/samba/private/krb5.conf': No such file or directory
+ systemctl stop firewalld
+ sed -i s/nameserver/#nameserver/ /etc/resolv.conf
+ echo 'nameserver 127.0.0.1'
+ flag=false
++ getenforce
++ grep Enforcing
+ '[' ']'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Mon Dec  5 08:11:12 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Mon Dec  5 08:11:12 2022 - INFO  - Start testing...
+ test_execution samba.service
+ service=samba.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-05 08:11:12'
+ test_restart samba.service
+ service=samba.service
+ systemctl restart samba.service
Failed to restart samba.service: Unit samba.service not found.
+ CHECK_RESULT 5 0 0 'samba.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='samba.service restart failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'samba.service restart failed'
+ LOG_ERROR 'samba.service restart failed'
+ message='samba.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service restart failed'
Mon Dec  5 08:11:13 2022 - ERROR - samba.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Mon Dec  5 08:11:14 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status samba.service
+ grep 'Active: active'
Unit samba.service could not be found.
+ CHECK_RESULT 1 0 0 'samba.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='samba.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'samba.service restart failed'
+ LOG_ERROR 'samba.service restart failed'
+ message='samba.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service restart failed'
Mon Dec  5 08:11:21 2022 - ERROR - samba.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Mon Dec  5 08:11:22 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop samba.service
Failed to stop samba.service: Unit samba.service not loaded.
+ CHECK_RESULT 5 0 0 'samba.service stop failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='samba.service stop failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'samba.service stop failed'
+ LOG_ERROR 'samba.service stop failed'
+ message='samba.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service stop failed'
Mon Dec  5 08:11:23 2022 - ERROR - samba.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Mon Dec  5 08:11:24 2022 - ERROR - ../common/common_lib.sh line 39
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status samba.service
+ grep 'Active: inactive'
Unit samba.service could not be found.
+ CHECK_RESULT 1 0 0 'samba.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='samba.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'samba.service stop failed'
+ LOG_ERROR 'samba.service stop failed'
+ message='samba.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service stop failed'
Mon Dec  5 08:11:30 2022 - ERROR - samba.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Mon Dec  5 08:11:31 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start samba.service
Failed to start samba.service: Unit samba.service not found.
+ CHECK_RESULT 5 0 0 'samba.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='samba.service start failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'samba.service start failed'
+ LOG_ERROR 'samba.service start failed'
+ message='samba.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service start failed'
Mon Dec  5 08:11:32 2022 - ERROR - samba.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Mon Dec  5 08:11:33 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status samba.service
+ grep 'Active: active'
Unit samba.service could not be found.
+ CHECK_RESULT 1 0 0 'samba.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='samba.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'samba.service start failed'
+ LOG_ERROR 'samba.service start failed'
+ message='samba.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service start failed'
Mon Dec  5 08:11:40 2022 - ERROR - samba.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Mon Dec  5 08:11:40 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled samba.service
+ service=samba.service
++ systemctl is-enabled samba.service
Failed to get unit file state for samba.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Mon Dec  5 08:11:41 2022 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2022-12-05 08:11:12' -u samba.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of samba.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of samba.service'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ sed -i 's\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS -d\' /usr/lib/systemd/system/samba.service
sed: can't read /usr/lib/systemd/system/samba.service: No such file or directory
+ systemctl daemon-reload
+ systemctl reload samba.service
Failed to reload samba.service: Unit samba.service not found.
+ CHECK_RESULT 5 0 0 'samba.service reload failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='samba.service reload failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'samba.service reload failed'
+ LOG_ERROR 'samba.service reload failed'
+ message='samba.service reload failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service reload failed'
Mon Dec  5 08:11:45 2022 - ERROR - samba.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_samba.sh line 62'
+ message='oe_test_service_samba.sh line 62'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_samba.sh line 62'
Mon Dec  5 08:11:46 2022 - ERROR - oe_test_service_samba.sh line 62
+ return 0
+ systemctl status samba.service
+ grep 'Active: active'
Unit samba.service could not be found.
+ CHECK_RESULT 1 0 0 'samba.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='samba.service reload causes the service status to change'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'samba.service reload causes the service status to change'
+ LOG_ERROR 'samba.service reload causes the service status to change'
+ message='samba.service reload causes the service status to change'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'samba.service reload causes the service status to change'
Mon Dec  5 08:11:47 2022 - ERROR - samba.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_samba.sh line 64'
+ message='oe_test_service_samba.sh line 64'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_samba.sh line 64'
Mon Dec  5 08:11:48 2022 - ERROR - oe_test_service_samba.sh line 64
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Mon Dec  5 08:11:49 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Dec  5 08:11:50 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Mon Dec  5 08:11:50 2022 - INFO  - start environment cleanup.
+ sed -i 's\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS -d\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS\' /usr/lib/systemd/system/samba.service
sed: can't read /usr/lib/systemd/system/samba.service: No such file or directory
+ systemctl daemon-reload
+ systemctl reload samba.service
Failed to reload samba.service: Unit samba.service not found.
+ systemctl stop samba.service
Failed to stop samba.service: Unit samba.service not loaded.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Mon Dec  5 08:11:55 2022 - WARN  - no thing to do.
+ return 0
+ sed -i '/nameserver 127.0.0.1/d' /etc/resolv.conf
+ sed -i s/#nameserver/nameserver/ /etc/resolv.conf
+ hostname anolis-riscv
+ sed -i /TESTAD/d /etc/hosts
+ systemctl start firewalld
A dependency job for firewalld.service failed. See 'journalctl -xe' for details.
+ '[' false = true ']'
+ rm -rf /etc/samba/smb.conf /var/lib/samba/private/msg.sock '/var/lib/samba/sysvol/*'
+ mv -f /etc/krb5.bak /etc/krb5.conf
+ mv -f /etc/samba/smb.conf_bak /etc/samba/smb.conf
mv: cannot stat '/etc/samba/smb.conf_bak': No such file or directory
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Mon Dec  5 08:11:56 2022 - INFO  - Finish environment cleanup!
