+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Sun Dec  4 08:18:12 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL ldirectord
+ pkgs=ldirectord
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs ldirectord --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpdibp9t7o
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpdibp9t7o
+ cp /usr/share/doc/ldirectord/ldirectord.cf /etc/ha.d/
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Sun Dec  4 08:19:14 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Sun Dec  4 08:19:15 2022 - INFO  - Start testing...
+ test_execution ldirectord.service
+ service=ldirectord.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-04 08:19:15'
+ test_restart ldirectord.service
+ service=ldirectord.service
+ systemctl restart ldirectord.service
Job for ldirectord.service failed because the control process exited with error code.
See "systemctl status ldirectord.service" and "journalctl -xeu ldirectord.service" for details.
+ CHECK_RESULT 1 0 0 'ldirectord.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service restart failed'
+ LOG_ERROR 'ldirectord.service restart failed'
+ message='ldirectord.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service restart failed'
Sun Dec  4 08:19:18 2022 - ERROR - ldirectord.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Sun Dec  4 08:19:19 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status ldirectord.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'ldirectord.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service restart failed'
+ LOG_ERROR 'ldirectord.service restart failed'
+ message='ldirectord.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service restart failed'
Sun Dec  4 08:19:26 2022 - ERROR - ldirectord.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Sun Dec  4 08:19:27 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop ldirectord.service
+ CHECK_RESULT 0 0 0 'ldirectord.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status ldirectord.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'ldirectord.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service stop failed'
+ LOG_ERROR 'ldirectord.service stop failed'
+ message='ldirectord.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service stop failed'
Sun Dec  4 08:19:34 2022 - ERROR - ldirectord.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Sun Dec  4 08:19:35 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start ldirectord.service
Job for ldirectord.service failed because the control process exited with error code.
See "systemctl status ldirectord.service" and "journalctl -xeu ldirectord.service" for details.
+ CHECK_RESULT 1 0 0 'ldirectord.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service start failed'
+ LOG_ERROR 'ldirectord.service start failed'
+ message='ldirectord.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service start failed'
Sun Dec  4 08:19:37 2022 - ERROR - ldirectord.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Sun Dec  4 08:19:38 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status ldirectord.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'ldirectord.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service start failed'
+ LOG_ERROR 'ldirectord.service start failed'
+ message='ldirectord.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service start failed'
Sun Dec  4 08:19:45 2022 - ERROR - ldirectord.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Sun Dec  4 08:19:46 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled ldirectord.service
+ service=ldirectord.service
++ systemctl is-enabled ldirectord.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ grep 'Created symlink'
++ systemctl enable ldirectord.service
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/ldirectord.service
+ find /etc/systemd/system/multi-user.target.wants/ldirectord.service
/etc/systemd/system/multi-user.target.wants/ldirectord.service
+ CHECK_RESULT 0 0 0 'ldirectord.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable ldirectord.service
Removed /etc/systemd/system/multi-user.target.wants/ldirectord.service.
+ find /etc/systemd/system/multi-user.target.wants/ldirectord.service
find: ‘/etc/systemd/system/multi-user.target.wants/ldirectord.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'ldirectord.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='ldirectord.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2022-12-04 08:19:15' -u ldirectord.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Dec 04 08:19:17 anolis-riscv ldirectord[769]: BEGIN failed--compilation aborted at /usr/sbin/ldirectord line 867.
Dec 04 08:19:17 anolis-riscv systemd[1]: ldirectord.service: Failed with result 'exit-code'.
Dec 04 08:19:17 anolis-riscv systemd[1]: Failed to start ldirectord.service - Monitor and administer real servers in a LVS cluster of load balanced virtual servers.
Dec 04 08:19:36 anolis-riscv ldirectord[785]: BEGIN failed--compilation aborted at /usr/sbin/ldirectord line 867.
Dec 04 08:19:37 anolis-riscv systemd[1]: ldirectord.service: Failed with result 'exit-code'.
Dec 04 08:19:37 anolis-riscv systemd[1]: Failed to start ldirectord.service - Monitor and administer real servers in a LVS cluster of load balanced virtual servers.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of ldirectord.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of ldirectord.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of ldirectord.service'
+ LOG_ERROR 'There is an error message for the log of ldirectord.service'
+ message='There is an error message for the log of ldirectord.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of ldirectord.service'
Sun Dec  4 08:19:54 2022 - ERROR - There is an error message for the log of ldirectord.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Sun Dec  4 08:19:55 2022 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ systemctl start ldirectord.service
Job for ldirectord.service failed because the control process exited with error code.
See "systemctl status ldirectord.service" and "journalctl -xeu ldirectord.service" for details.
+ sed -i 's\ExecStart=/usr/sbin/ldirectord\ExecStart=/usr/sbin/ldirectord -d\g' /usr/lib/systemd/system/ldirectord.service
+ systemctl daemon-reload
+ systemctl reload ldirectord.service
ldirectord.service is not active, cannot reload.
+ CHECK_RESULT 1 0 0 'ldirectord.service reload failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service reload failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service reload failed'
+ LOG_ERROR 'ldirectord.service reload failed'
+ message='ldirectord.service reload failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service reload failed'
Sun Dec  4 08:20:01 2022 - ERROR - ldirectord.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ldirectord.sh line 36'
+ message='oe_test_service_ldirectord.sh line 36'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ldirectord.sh line 36'
Sun Dec  4 08:20:02 2022 - ERROR - oe_test_service_ldirectord.sh line 36
+ return 0
+ systemctl status ldirectord.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'ldirectord.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='ldirectord.service reload causes the service status to change'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'ldirectord.service reload causes the service status to change'
+ LOG_ERROR 'ldirectord.service reload causes the service status to change'
+ message='ldirectord.service reload causes the service status to change'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'ldirectord.service reload causes the service status to change'
Sun Dec  4 08:20:03 2022 - ERROR - ldirectord.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_ldirectord.sh line 38'
+ message='oe_test_service_ldirectord.sh line 38'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_ldirectord.sh line 38'
Sun Dec  4 08:20:04 2022 - ERROR - oe_test_service_ldirectord.sh line 38
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Sun Dec  4 08:20:05 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sun Dec  4 08:20:06 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Sun Dec  4 08:20:07 2022 - INFO  - start environment cleanup.
+ sed -i 's\ExecStart=/usr/sbin/ldirectord -d\ExecStart=/usr/sbin/ldirectord\g' /usr/lib/systemd/system/ldirectord.service
+ systemctl daemon-reload
+ systemctl reload ldirectord.service
ldirectord.service is not active, cannot reload.
+ systemctl stop ldirectord.service
+ rm -rf /etc/ha.d/ldirectord.cf
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpdibp9t7o ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpdibp9t7o
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Sun Dec  4 08:20:31 2022 - INFO  - Finish environment cleanup!
